const abilities=['Flying','Reach','Menace','First strike','Double strike','Trample','Deathtouch','Lifelink','Vigilance','Indestructible'];
const state={mode:'calculator',next:1,attackers:[],blockers:[]};
const $=s=>document.querySelector(s); const esc=s=>String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
function add(type){const item={id:state.next++,name:type==='attacker'?`Attacker ${state.next-1}`:`Blocker ${state.next-1}`,power:2,toughness:2,abilities:[],target:''};state[type+'s'].push(item);render()}
function render(){renderCards('attacker');renderCards('blocker');calculate()}
function renderCards(type){const list=state[type+'s'];const host=$('#'+type+'s');host.innerHTML=list.length?'':'<p class="empty">Nothing added yet.</p>';list.forEach(c=>{const abilitiesHtml=abilities.map(a=>`<button class="ability ${c.abilities.includes(a)?'on':''}" data-id="${c.id}" data-type="${type}" data-ability="${a}">${a}</button>`).join('');let assignment='';if(type==='attacker'){assignment=`<label class="assign">Blocked by<select data-field="target" data-id="${c.id}" data-type="attacker"><option value="">Unblocked</option>${state.blockers.map(b=>`<option value="${b.id}" ${c.target==b.id?'selected':''}>${esc(b.name)}</option>`).join('')}</select></label>`}host.insertAdjacentHTML('beforeend',`<article class="creature"><button class="remove" data-remove="${type}" data-id="${c.id}">×</button><h4>${esc(c.name)}</h4><div class="stats"><input type="number" min="0" data-field="power" data-id="${c.id}" data-type="${type}" value="${c.power}" aria-label="Power"><span>/</span><input type="number" min="1" data-field="toughness" data-id="${c.id}" data-type="${type}" value="${c.toughness}" aria-label="Toughness"></div><div class="abilities">${abilitiesHtml}</div>${assignment}</article>`)})}
function find(type,id){return state[type+'s'].find(x=>x.id==id)}
function calculate(){let lines=['> COMBAT DAMAGE CALCULATION','>'];if(!state.attackers.length)lines.push('> Add an attacker to begin.');let total=0;state.attackers.forEach(a=>{const b=find('blocker',a.target);let power=+a.power;lines.push(`> ${a.name}: ${power} base power.`);if(a.abilities.includes('Double strike'))lines.push('> Double strike: first-strike and regular damage apply.');if(b){let lethal=a.abilities.includes('Deathtouch')?1:Math.min(power,+b.toughness);let trample=a.abilities.includes('Trample')?Math.max(0,power-lethal):0;total+=trample;lines.push(`> Blocked by ${b.name} (${b.power}/${b.toughness}).`);lines.push(`> ${a.name} assigns ${lethal} damage to ${b.name}.`);if(trample)lines.push(`> Trample carries ${trample} damage through to the defending player.`);lines.push(`> ${b.name} would ${lethal>=+b.toughness?'be destroyed':'survive'} combat.`)}else{total+=power;lines.push(`> Unblocked: ${power} damage reaches the defending player.`)}if(a.abilities.includes('Lifelink'))lines.push(`> Lifelink: the attacking player gains ${power} life.`);if(a.abilities.includes('First strike')||a.abilities.includes('Double strike'))lines.push('> Resolve first-strike damage before regular combat damage.');lines.push('>')});lines.push(`> TOTAL DAMAGE TO PLAYER: ${total}`);$('#terminal').textContent=lines.join('\n');$('#status').textContent=state.attackers.length?'UPDATED':'READY'}
document.addEventListener('click',e=>{const t=e.target;if(t.id==='addAttacker')add('attacker');if(t.id==='addBlocker')add('blocker');if(t.id==='resetButton'){state.attackers=[];state.blockers=[];render()}if(t.dataset.remove){state[t.dataset.remove+'s']=state[t.dataset.remove+'s'].filter(x=>x.id!=t.dataset.id);state.attackers.forEach(a=>{if(!find('blocker',a.target))a.target='' });render()}if(t.dataset.ability){const c=find(t.dataset.type,t.dataset.id);c.abilities.includes(t.dataset.ability)?c.abilities=c.abilities.filter(a=>a!==t.dataset.ability):c.abilities.push(t.dataset.ability);render() }if(t.id==='helpButton')$('#helpDialog').showModal();if(t.id==='closeHelp')$('#helpDialog').close();if(t.dataset.mode){state.mode=t.dataset.mode;document.querySelectorAll('.mode').forEach(x=>x.classList.toggle('active',x.dataset.mode===state.mode));$('#modeLabel').textContent=state.mode.toUpperCase()+' MODE';$('#modeTitle').textContent=state.mode==='practice'?'Answer the combat.':'Count the combat.';$('#modeDescription').textContent=state.mode==='practice'?'Build the response, predict the result, then compare it with the calculation.':'Build a simple combat, assign blockers, and inspect the rules-aware calculation.'}});
document.addEventListener('input',e=>{const t=e.target;if(t.dataset.field){const c=find(t.dataset.type,t.dataset.id);c[t.dataset.field]=t.value;calculate()}});document.addEventListener('change',e=>{const t=e.target;if(t.dataset.field){find(t.dataset.type,t.dataset.id)[t.dataset.field]=t.value;calculate()}});render();
